### ISSUE TITLE
Newbie questions

### ISSUE THREAD

**Issue by ubersan** [optapy/optapy#139]
Hi team,

Thanks a lot for this awesome project, I love that you put in the big effort to provide a :snake:  wrapper! :hugs: 

A few questions have popped up while starting to get familiar with the whole OptaPlanner and OptaPy projects and I couldn't find these details in any of the docs/readme's:
* If OptaPy is "just" a wrapper around the JVM code, how can it be that much slower (I think you're mentioning roughly 20%)? I'd be interested in understanding what/why the extra work has to be done
* I assume the slow-down is similar for all use cases (as I'm mainly interested in the timetabling one)?
* I know you're working hard on closing on the performance gap, but could you make some estimations in regards to a) timelines and b) eventual outcome (meaning, performance gap can be almost/completely/never fully closed)?
* This might be in the docs, but just to be sure before hitting a blocker a few months into this :sweat_smile: : Is the whole Java API covered by OptaPy or are some parts not (yet) supported? How are the two API's evolving?

Thanks again for all the work you put into this, this whole project is just awesome :1st_place_medal:

**Comment by Christopher-Chianelli** [comment]
- OptaPy is "just" a wrapper for the JVM code, the slowness comes when comparing equivalent CPython constraints to Java constraints. Unlike other optimization libraries which requires your constraints to be mathematical expressions, you can execute arbitrary functions with OptaPlanner/OptaPy. Previously, there was a massive performance cost from the overhead of repeatedly calling a CPython function in Java (around 100 CPython bytecode executions, and when most functions are around 4 python bytecodes, leads to a massive increases in runtime (around 20 times, not 20%). This was fixed by.... implementing a CPython bytecode translator: https://github.com/optapy/optapy/pull/108. The remaining slowdowns comes from 1. the translation not being as optimized as it could be (favouring correctness over speed) and 2. CPython semantics preventing optimization/being slower than Java semantics.
- The slowdown varies; it depends on how well the translated function compares to the same function in Java.
- The main work for performance improvement is merged/finished (the translator). Future work is more focused on implementing/exposing the remaining OptaPlanner API in OptaPy.
- Some parts are not supported/exposed yet. The missing parts should be listed in https://github.com/optapy/optapy/issues/74. The goal is to have all of OptaPlanner API accessible in OptaPy eventually. OptaPlanner API also continues to evolve, and get new features, which will (eventually) make their way into OptaPy.

**Comment by ubersan** [comment]
Thanks a bunch  @Christopher-Chianelli for the quick & clear answers, this resolves all my open points :+1:

**Comment by ubersan** [comment]
@Christopher-Chianelli The readme [still reads](https://github.com/optapy/optapy/blob/main/README.md?plain=1#L16)

> but using OptaPy in Python is significantly slower than using OptaPlanner in Java or Kotlin

Should this then be updated?

**Comment by Christopher-Chianelli** [comment]
It there to note that writing the same constraint in Java/Kotlin will likely be significantly faster. Although the performance was significantly improved, complicated constraints that are not just `get this attribute`/`compare this attribute/test this attribute` (although these are the most common constraints) will likely be faster in Java, because Java semantics allows for significant speed up compared to Python semantics. For instance, in Python, `a + b` translates (roughly) to this:
```python
a_type = type(a)
b_type = type(b)
if hasattr(a_type, '__add__'):
    result = a_type.__add__(a, b)
    if result is NotImplemented and hasattr(b_type, '__radd__'):
        result = b_type.__radd__(b, a)
        if result is NotImplemented:
            raise TypeError(f'Incompatible type for +: {a_type}, {b_type}')
elif hasattr(b_type, '__radd__'):
    result = b_type.__radd__(b, a)
    if result is NotImplemented:
        raise TypeError(f'Incompatible type for +: {a_type}, {b_type}')
else:
    raise TypeError(f'Incompatible type for +: {a_type}, {b_type}')
```

In Java, it is either a direct method call (if types are not numeric) or a single opcode (if the types are numeric). We do try to optimize binary ops by converting them to a direct method call if the types of the objects are known (via type annotation or type flow analysis), but it is not always possible.

**Comment by ubersan** [comment]
Ah ok, now I understand what the pure wrapper part and where the actual transpilation kicks in. I indeed started to experiment with non-trivial constraints, and the solutions/sec dropped significantly. I guess there is usually room to modify the model a bit to work around and keep the constraints somewhat simple-ish, but eventually you'll feel the impact of this.

Thanks for the detailed answers and explanations :+1:
