### ISSUE TITLE
Can't run after installing with pip

### ISSUE THREAD

**Issue by ScDor** [optapy/optapy#14]
EDIT: the cause is that I ran a file called `optapy.py`, hence the circular import. 

---

Hey,

I installed with `pip` (rather than built it myself, which might've been a mistake?)
When running a file with the following content
```
from optapy import problem_fact

@problem_fact
class Timeslot:
    def __init__(self, id, dayOfWeek, startTime, endTime):
        self.id = id
        self.dayOfWeek = dayOfWeek
        self.startTime = startTime
        self.endTime = endTime
```

I get
```
from optapy import problem_fact
ImportError: cannot import name 'problem_fact' from partially initialized module 'optapy' (most likely due to a circular import) (C:\Users\....\optapy.py)
```

Is it my bad of using pip to install? If so, warning new users about it on the `getting started` page would be appreciated.

Thanks

**Comment by Christopher-Chianelli** [comment]
Is your test file called `optapy.py` (or is there a file called optapy.py in your directory)? If so, the issue is explained by https://stackoverflow.com/a/66055075 , where it tries to use your local file to resolve the import instead of the dependency; The version from pip works (it is used in the notebook and tested locally).

**Comment by ScDor** [comment]
you're right, thanks :)
