### ISSUE TITLE
__init__.py has no reference of some functions.

### ISSUE THREAD

**Issue by sakibraza-oodles** [optapy/optapy#163]
![Screenshot from 2023-04-06 16-32-01](https://user-images.githubusercontent.com/109201996/230358697-764d6bfe-4239-401f-8749-bef9c1bb1e92.png)
It  throws the error there is no reference of HardSoftScore, Duration, SolverStatus etc in __init__.py in optapy8.31.1b0.

**Comment by Christopher-Chianelli** [comment]
This is probably because `Duration`, `HardSoftScore`, and `SolverStatus` are pure Java types that are imported through JPype's import system; the imports do exist (for example, https://github.com/optapy/optapy/blob/4e3c823c72d5f99e3f1e606ed3f3d9f1c10ac84b/optapy-core/src/main/python/types/types.py#L21 ). We do generate stubs (https://github.com/optapy/optapy/blob/main/create-stubs.py) so type checkers are able to find their definition, although looking at the wheel, it appear they are missing; will investigate.
