### ISSUE TITLE
Is setMoveThreadCount method working?

### ISSUE THREAD

**Issue by Stanpol** [optapy/optapy#46]
Thank you for the optapy, really great API and a pleasure to work with.

I know it's not production ready and slow, but I was thinking to try to utilize multiple threads to speed up the moves/optimization. Is it possible? So far I tried the following methods: 
`.setMoveThreadCount('5')` 
`.setMoveThreadCount('AUTO')`
`.withMoveThreadCount( ...not sure which python object should go here... )`  

But the optimization never starts. Is that just my machine or this is not ready yet?

**Comment by Christopher-Chianelli** [comment]
Right now, the code directly executes in Python. And due to how Python currently works, only one thread is run at a time, no matter the number of cores on the computer. What this means is using multiple move threads actually slows down the solver currently, as they all are contending for the Python global interpreter lock. So for move thread count to improve performance, one of these things must happen:

- Python remove the global interpreter lock. IIRC, this is ongoing work and is not yet in any Python release.
- OptaPy runs all user code in Java. This involves translating Python bytecode to Java bytecode when the ConstraintProvider is created. This should massively improve performance (even outside multi-threading), but would take a couple of months to implement fully and correctly.

The examples you gave are all correct ways to set the move thread count. But you still need to create the solver from the SolverConfig and start the solver (example from modifying `optapy-quickstarts/school-timetabling/main.py`:

```python
solver_config = SolverConfig().withEntityClasses(get_class(Lesson)) \
    .withSolutionClass(get_class(TimeTable)) \
    .withConstraintProviderClass(get_class(define_constraints)) \
    .withMoveThreadCount('2') \
    .withTerminationSpentLimit(Duration.ofSeconds(30))

solver = solver_factory_create(solver_config).buildSolver()

solution = solver.solve(generate_problem())
```

**Comment by Christopher-Chianelli** [comment]
@Stanpol With the latest release (8.28.0b0), OptaPy now comes with a builtin bytecode translator that is automatically used. Beside massively increasing single-threaded performance, because all the code now runs in Java, multi-threaded solving will increase performance (as now the GIL can be fully bypassed).
